###ユーザー情報取得
GET http://localhost:8000/api/users/1
Accept: application/json ###クライアントがJsonを受け付ける指定

###ユーザー一覧取得
GET http://localhost:8000/api/users?min_level=3&max_level=9
Accept: application/json


###アイテム一覧取得
GET http://localhost:8000/api/items
Accept: application/json


###マスターメール一覧
GET http://localhost:8000/api/mails
Accept: application/json

###ユーザーの所持アイテムリスト
GET http://localhost:8000/api/user_items/1
Accept: application/json

###ユーザーメール受信一覧
GET http://localhost:8000/api/user_mail/1
Accept: application/json
