###ユーザー情報取得
GET https://api-cube-puzzle.japaneast.cloudapp.azure.com/api/users/1
Accept: application/json ###クライアントがJsonを受け付ける指定
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###ユーザー一覧取得
GET https://api-cube-puzzle.japaneast.cloudapp.azure.com/api/users?min_level=1&max_level=9
Accept: application/json
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###アイテム一覧取得
GET http://localhost:8000/api/items
Accept: application/json
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###マスターメール一覧
GET http://localhost:8000/api/mails
Accept: application/json
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###ユーザーの所持アイテムリスト
GET http://localhost:8000/api/user_items/1
Accept: application/json
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###ユーザーメール受信一覧
GET http://localhost:8000/api/user_mail/1
Accept: application/json
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###フォロー一覧
GET http://localhost:8000/api/users_follow/1
Accept: application/json
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###フォローの登録
POST http://localhost:8000/api/users_follow/store
Content-Type: application/json
Accept: application/json

{
    "user_id":1,
    "follow_user_id":2,
    "action": 1
}

###フォローの解除
POST http://localhost:8000/api/users_follow/delete/1
Content-Type: application/json
Accept: application/json

{
    "follow_user_id": 3,
    "action": 2
}

###ユーザー登録
POST https://api-cube-puzzle.japaneast.cloudapp.azure.com/api/users/store
Content-Type: application/json
Accept: application/json

{
 "name":"cc",
    "level": 1,
    "exp": 2
}

###既存のユーザーのトークン生成
POST http://localhost:8000/api/users/Token
Content-Type: application/json
Accept: application/json

{
    "user_id":110
}


###ユーザーの更新
POST http://localhost:8000/api/users/update
Content-Type: application/json
Accept: application/json

{
    "user_id": 102,
    "name":"jobi2",
    "level": 3,
    "exp": 5
}

###ステージ毎の最短手数取得
GET http://localhost:8000/api/stage/1
Accept: application/json
Authorization: Bearer 1|LjFNf4rRpykUFCpyrjUF6dMDQfA3oK3dyS0DhHAa825b40b7 ###トークン認証をするときは必須

###自分自身の最短手数取得
GET http://localhost:8000/api/min_hand_stage/102/102
Accept: application/json
Authorization: Bearer 1|LjFNf4rRpykUFCpyrjUF6dMDQfA3oK3dyS0DhHAa825b40b7  ###トークン認証をするときは必須

###ステージクリアの登録
POST http://localhost:8000/api/stage/store
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|LjFNf4rRpykUFCpyrjUF6dMDQfA3oK3dyS0DhHAa825b40b7  ###トークン認証をするときは必須

{
    "stage_id": 102,
    "user_id": 102,
    "result":1,
    "min_hand_num": 3
}

###島の一覧情報
GET http://localhost:8000/api/land/index
Accept: application/json
Authorization: Bearer 11|8HMwK9DzbL7Cake3ExINS1bV0xMzwl4fdL43rVbC0ab0f151 ###トークン認証をするときは必須

###島の詳細情報
GET http://localhost:8000/api/land/show/11
Accept: application/json
Authorization: Bearer 1|LjFNf4rRpykUFCpyrjUF6dMDQfA3oK3dyS0DhHAa825b40b7 ###トークン認証をするときは必須

###島の状況の登録
POST http://localhost:8000/api/land_block/store
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|LjFNf4rRpykUFCpyrjUF6dMDQfA3oK3dyS0DhHAa825b40b7 ###トークン認証をするときは必須

{
    "land_id":2,
    "user_id": 2,
    "land_block_num": 100
}

###ブロックの情報取得
GET http://localhost:8000/api/block/1
Accept: application/json
Authorization: Bearer 1|nSWh8mYZ1gDREDturfxHRuGrZkO96XVndS2WYgbSe5e7ab29 ###トークン認証をするときは必須

###ブロックの情報を登録
POST http://localhost:8000/api/block/store
Content-Type: application/json
Accept: application/json

{
    "land_id":1,
    "block_user_id": 1,
    "type": "ab",
    "x_Direction": 1,
    "z_Direction": 1
}
