###ユーザー情報取得
GET http://localhost:8000/api/users/1
Accept: application/json ###クライアントがJsonを受け付ける指定

###ユーザー一覧取得
GET http://localhost:8000/api/users?min_level=1&max_level=9
Accept: application/json

###アイテム一覧取得
GET http://localhost:8000/api/items
Accept: application/json

###マスターメール一覧
GET http://localhost:8000/api/mails
Accept: application/json

###ユーザーの所持アイテムリスト
GET http://localhost:8000/api/user_items/1
Accept: application/json

###ユーザーメール受信一覧
GET http://localhost:8000/api/user_mail/1
Accept: application/json

###フォロー一覧
GET http://localhost:8000/api/users_follow/1
Accept: application/json

###フォローの登録
POST http://localhost:8000/api/users_follow/store
Content-Type: application/json
Accept: application/json

{
    "user_id":1,
    "follow_user_id":2,
    "action": 1
}

###フォローの解除
POST http://localhost:8000/api/users_follow/delete/1
Content-Type: application/json
Accept: application/json

{
    "follow_user_id": 3,
    "action": 2
}

###ユーザー登録
POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json

{
 "name":"jobi",
    "level": 1,
    "exp": 2
}


###ユーザーの更新
POST http://localhost:8000/api/users/update
Content-Type: application/json
Accept: application/json

{
    "user_id": 102,
    "name":"jobi2",
    "level": 3,
    "exp": 5
}


###ステージマスタ
GET http://localhost:8000/api/stage/
Accept: application/json

###島の情報
GET http://localhost:8000/api/land/
Accept: application/json

###ブロックの情報取得
GET http://localhost:8000/api/block/1
Accept: application/json

###ブロックの情報を登録
POST http://localhost:8000/api/block/store
Content-Type: application/json
Accept: application/json

{
    "land_id":1,
    "block_user_id": 1,
    "type": "ab",
    "x_Direction": 1,
    "z_Direction": 1
}
